# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c1392c2747790506475ffd8bc2701fc53a9debf45c70617cf7e16c4d80840820c5ba9082aeac559b8c5c125c2fecfebed99c2f5ffab5042b4dcc473bb97b5f5

test:
  secret_key_base: 0e3068fd5a227c59e8c4685a24ab08e22627cdb1f81a4006e7ed2736cd935f45f31a79d0043dfeca6b92fd4eaf452078df7ffd6f5fdacddaf5afc0117188db54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
